"""SVG to G-code conversion (basic).

Converts SVG vector paths to G-code for laser cutting.
Uses svgpathtools for parsing SVG paths.
"""

from typing import List, Optional

try:
    from svgpathtools import svg2paths, Line, Arc, CubicBezier, QuadraticBezier
    HAS_SVG = True
except ImportError:
    HAS_SVG = False


def svg_to_gcode(
    svg_path: str,
    feed_rate: float = 500,
    power: int = 1000,
    travel_speed: float = 3000,
    scale: float = 1.0,
    offset_x: float = 0.0,
    offset_y: float = 0.0,
    bezier_resolution: int = 20,
    laser_mode: bool = True,
) -> List[str]:
    """Convert an SVG file to G-code lines.

    Requires svgpathtools (`pip install svgpathtools`).
    """
    if not HAS_SVG:
        return ["; ERROR: svgpathtools not installed. Run: pip install svgpathtools"]

    paths, attributes = svg2paths(svg_path)

    gcode = []
    gcode.append("; Generated by PyLaserGRBL — SVG conversion")
    gcode.append(f"; Source: {svg_path}")
    gcode.append("G90")
    gcode.append("G21")
    laser_cmd = "M4" if laser_mode else "M3"
    gcode.append(f"{laser_cmd} S0")

    for path in paths:
        if len(path) == 0:
            continue

        # Move to start of path
        start = path[0].start
        sx = start.real * scale + offset_x
        sy = start.imag * scale + offset_y
        gcode.append(f"G0 X{sx:.4f} Y{sy:.4f}")

        for segment in path:
            if isinstance(segment, Line):
                ex = segment.end.real * scale + offset_x
                ey = segment.end.imag * scale + offset_y
                gcode.append(f"G1 X{ex:.4f} Y{ey:.4f} S{power} F{feed_rate:.0f}")

            elif isinstance(segment, (CubicBezier, QuadraticBezier)):
                # Approximate bezier with line segments
                for i in range(1, bezier_resolution + 1):
                    t = i / bezier_resolution
                    pt = segment.point(t)
                    px = pt.real * scale + offset_x
                    py = pt.imag * scale + offset_y
                    gcode.append(f"G1 X{px:.4f} Y{py:.4f} S{power} F{feed_rate:.0f}")

            elif isinstance(segment, Arc):
                # Approximate arc with line segments
                for i in range(1, bezier_resolution + 1):
                    t = i / bezier_resolution
                    pt = segment.point(t)
                    px = pt.real * scale + offset_x
                    py = pt.imag * scale + offset_y
                    gcode.append(f"G1 X{px:.4f} Y{py:.4f} S{power} F{feed_rate:.0f}")

        # Laser off between paths
        gcode.append("G0 S0")

    gcode.append("M5")
    gcode.append("G0 X0 Y0")
    return gcode
